### ISSUE TITLE
Energy Weapons Cut down to size

### ISSUE THREAD

**Issue by Wateronix** [f13babylon/f13babylon#357]
![image](https://github.com/f13babylon/f13babylon/assets/63539643/66d87361-ce3a-42d5-9435-661d326e7165)
The sprites used arnt bad, but it is stupid to have all weapons be super sized, 
Used the shrink ray on the AEP7 and AER9, if you like it i can see to changing the others aswell.
![image](https://github.com/f13babylon/f13babylon/assets/63539643/52d70822-a6d4-4fcb-91ff-0858ad02053b)

**Comment by Draganfrukts** [comment]
This completely ruins any semblance of detail the sprites could've ever hoped to have

**Comment by mopcat** [comment]
this sucks

**Comment by Wateronix** [comment]
Of course, that is how pixel art works.
SS13 uses 32x32, so 32x48 has space for 50% more detail, but it will clip out when in your inventory and pistols on the ground will be huge.

**Comment by Draganfrukts** [comment]
> Of course, that is how pixel art works. SS13 uses 32x32, so 32x48 has space for 50% more detail, but it will clip out when in your inventory and pistols on the ground will be huge.

The decision to make the sprites 48x32 was taken explicitly to avoid returning to the eternal slop that is mediocre diagonal sprites and smushed guns, these just look like the old uglier rifles but with a messed up palette because the only thing that was done to them was the application of a tool with complete disregard for how the end product would look. Resizing sprites that were meant to be a certain size just makes them ugly.

**Comment by Draganfrukts** [comment]
Furthermore: we're working on changing the position of the guns to stop them from sticking far past the tile when they don't explicitly breach 32 pixels in length.
The only justification I'm seeing is "It's stupid because they're too big" and it's frankly far from enough. We can afford to make assets that look pretty instead of utilitarian.

**Comment by Wateronix** [comment]
I can agree with rifles, but with a nearly square pistol, it just looks ridiculos.

**Comment by mazzinsanity** [comment]
This sucks

**Comment by ApplePlastic** [comment]
this peaks

**Comment by ThyBaron** [comment]
I do think this is something necessary to do, and something I did ask internally to be done some time ago, though, the reality of doing it seems more complicated and understandably this does compress the details! Though — having them be American meal portion sized needs some downsizing! The sprites are lovely and I'd lather them up in kisses if I could

**Comment by Wateronix** [comment]
Yeah the sprites definitly are good.

So if I continue finishing the sprites up, will they be merged in?
Want all to be cut down? Or just pistols? And will it be fine if I push it pice meal, or want it in one go?
If you want it all in one go, it will take a while.

**Comment by mazzinsanity** [comment]
Tweaked as of #359
